// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Data _$DataFromJson(Map<String, dynamic> json) => Data(
      productSeriesId: json['productSeriesId'] as String?,
      productId: json['productId'] as String?,
      productCode: json['productCode'] as String?,
      productName: json['productName'] as String?,
      productImage: json['productImage'] as String?,
      productAbbreviateImage: json['productAbbreviateImage'] as String?,
      productDetailsImage: json['productDetailsImage'] as String?,
      productShareImage: json['productShareImage'] as String?,
      price: json['price'] as int?,
      issueNumber: json['issueNumber'] as String?,
      circulateNumber: json['circulateNumber'] as int?,
      contractAddress: json['contractAddress'] as String?,
      chainMark: json['chainMark'] as String?,
      creatorId: json['creatorId'] as String?,
      creatorAvatar: json['creatorAvatar'] as String?,
      creatorNickName: json['creatorNickName'] as String?,
      creatorWalletAddress: json['creatorWalletAddress'],
      creatorIntroduce: json['creatorIntroduce'] as String?,
      brandPartyId: json['brandPartyId'],
      brandPartyAvatar: json['brandPartyAvatar'],
      brandPartyNickName: json['brandPartyNickName'],
      brandPartyIntroduce: json['brandPartyIntroduce'],
      supervisorId: json['supervisorId'],
      supervisorAvatar: json['supervisorAvatar'],
      supervisorNickName: json['supervisorNickName'],
      supervisorIntroduce: json['supervisorIntroduce'],
      productDescription: json['productDescription'] as String?,
      holderId: json['holderId'] as String?,
      holderAvatar: json['holderAvatar'] as String?,
      holderNickName: json['holderNickName'] as String?,
      holderWalletAddress: json['holderWalletAddress'] as String?,
      status: json['status'] as int?,
      synthesisStatus: json['synthesisStatus'] as int?,
      activityStatus: json['activityStatus'],
      transferType: json['transferType'] as int?,
      allowSellTime: json['allowSellTime'] as String?,
      isResale: json['isResale'] as int?,
      onSales: json['onSales'],
      stock: json['stock'],
      isRestrictionSell: json['isRestrictionSell'] as int?,
      payWay: json['payWay'] as String?,
      isProductBatchTransfer: json['isProductBatchTransfer'] as int?,
      isUserBatchTransfer: json['isUserBatchTransfer'] as int?,
      type: json['type'] as int?,
      isBoxPrize: json['isBoxPrize'] as int?,
      notOpenNumber: json['notOpenNumber'],
      productList: json['productList'],
      dynamicImage: json['dynamicImage'],
      batchResale: json['batchResale'] as int?,
    );

Map<String, dynamic> _$DataToJson(Data instance) => <String, dynamic>{
      'productSeriesId': instance.productSeriesId,
      'productId': instance.productId,
      'productCode': instance.productCode,
      'productName': instance.productName,
      'productImage': instance.productImage,
      'productAbbreviateImage': instance.productAbbreviateImage,
      'productDetailsImage': instance.productDetailsImage,
      'productShareImage': instance.productShareImage,
      'price': instance.price,
      'issueNumber': instance.issueNumber,
      'circulateNumber': instance.circulateNumber,
      'contractAddress': instance.contractAddress,
      'chainMark': instance.chainMark,
      'creatorId': instance.creatorId,
      'creatorAvatar': instance.creatorAvatar,
      'creatorNickName': instance.creatorNickName,
      'creatorWalletAddress': instance.creatorWalletAddress,
      'creatorIntroduce': instance.creatorIntroduce,
      'brandPartyId': instance.brandPartyId,
      'brandPartyAvatar': instance.brandPartyAvatar,
      'brandPartyNickName': instance.brandPartyNickName,
      'brandPartyIntroduce': instance.brandPartyIntroduce,
      'supervisorId': instance.supervisorId,
      'supervisorAvatar': instance.supervisorAvatar,
      'supervisorNickName': instance.supervisorNickName,
      'supervisorIntroduce': instance.supervisorIntroduce,
      'productDescription': instance.productDescription,
      'holderId': instance.holderId,
      'holderAvatar': instance.holderAvatar,
      'holderNickName': instance.holderNickName,
      'holderWalletAddress': instance.holderWalletAddress,
      'status': instance.status,
      'synthesisStatus': instance.synthesisStatus,
      'activityStatus': instance.activityStatus,
      'transferType': instance.transferType,
      'allowSellTime': instance.allowSellTime,
      'isResale': instance.isResale,
      'onSales': instance.onSales,
      'stock': instance.stock,
      'isRestrictionSell': instance.isRestrictionSell,
      'payWay': instance.payWay,
      'isProductBatchTransfer': instance.isProductBatchTransfer,
      'isUserBatchTransfer': instance.isUserBatchTransfer,
      'type': instance.type,
      'isBoxPrize': instance.isBoxPrize,
      'notOpenNumber': instance.notOpenNumber,
      'productList': instance.productList,
      'dynamicImage': instance.dynamicImage,
      'batchResale': instance.batchResale,
    };
