// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Data _$DataFromJson(Map<String, dynamic> json) => Data(
      productSeriesId: json['productSeriesId'] as String?,
      productId: json['productId'] as String?,
      productCode: json['productCode'],
      productName: json['productName'] as String?,
      productImage: json['productImage'] as String?,
      productAbbreviateImage: json['productAbbreviateImage'] as String?,
      productDetailsImage: json['productDetailsImage'] as String?,
      productShareImage: json['productShareImage'] as String?,
      price: (json['price'] as num?)?.toDouble(),
      issueNumber: json['issueNumber'] as String?,
      circulateNumber: json['circulateNumber'] as int?,
      contractAddress: json['contractAddress'],
      chainMark: json['chainMark'],
      creatorId: json['creatorId'] as String?,
      creatorAvatar: json['creatorAvatar'] as String?,
      creatorNickName: json['creatorNickName'] as String?,
      creatorWalletAddress: json['creatorWalletAddress'],
      creatorIntroduce: json['creatorIntroduce'] as String?,
      brandPartyId: json['brandPartyId'] as String?,
      brandPartyAvatar: json['brandPartyAvatar'] as String?,
      brandPartyNickName: json['brandPartyNickName'] as String?,
      brandPartyIntroduce: json['brandPartyIntroduce'] as String?,
      supervisorId: json['supervisorId'] as String?,
      supervisorAvatar: json['supervisorAvatar'] as String?,
      supervisorNickName: json['supervisorNickName'] as String?,
      supervisorIntroduce: json['supervisorIntroduce'] as String?,
      productDescription: json['productDescription'] as String?,
      holderId: json['holderId'],
      holderAvatar: json['holderAvatar'],
      holderNickName: json['holderNickName'],
      holderWalletAddress: json['holderWalletAddress'],
      status: json['status'],
      synthesisStatus: json['synthesisStatus'],
      activityStatus: json['activityStatus'] as int?,
      transferType: json['transferType'],
      allowSellTime: json['allowSellTime'],
      isResale: json['isResale'],
      onSales: json['onSales'] as int?,
      stock: json['stock'] as int?,
      isRestrictionSell: json['isRestrictionSell'],
      payWay: json['payWay'],
      isProductBatchTransfer: json['isProductBatchTransfer'],
      isUserBatchTransfer: json['isUserBatchTransfer'],
      type: json['type'] as int?,
      isBoxPrize: json['isBoxPrize'] as int?,
      notOpenNumber: json['notOpenNumber'] as int?,
      productList: (json['productList'] as List<dynamic>?)
          ?.map((e) => ProductList.fromJson(e as Map<String, dynamic>))
          .toList(),
      dynamicImage: json['dynamicImage'] == null
          ? null
          : DynamicImage.fromJson(json['dynamicImage'] as Map<String, dynamic>),
    );

Map<String, dynamic> _$DataToJson(Data instance) => <String, dynamic>{
      'productSeriesId': instance.productSeriesId,
      'productId': instance.productId,
      'productCode': instance.productCode,
      'productName': instance.productName,
      'productImage': instance.productImage,
      'productAbbreviateImage': instance.productAbbreviateImage,
      'productDetailsImage': instance.productDetailsImage,
      'productShareImage': instance.productShareImage,
      'price': instance.price,
      'issueNumber': instance.issueNumber,
      'circulateNumber': instance.circulateNumber,
      'contractAddress': instance.contractAddress,
      'chainMark': instance.chainMark,
      'creatorId': instance.creatorId,
      'creatorAvatar': instance.creatorAvatar,
      'creatorNickName': instance.creatorNickName,
      'creatorWalletAddress': instance.creatorWalletAddress,
      'creatorIntroduce': instance.creatorIntroduce,
      'brandPartyId': instance.brandPartyId,
      'brandPartyAvatar': instance.brandPartyAvatar,
      'brandPartyNickName': instance.brandPartyNickName,
      'brandPartyIntroduce': instance.brandPartyIntroduce,
      'supervisorId': instance.supervisorId,
      'supervisorAvatar': instance.supervisorAvatar,
      'supervisorNickName': instance.supervisorNickName,
      'supervisorIntroduce': instance.supervisorIntroduce,
      'productDescription': instance.productDescription,
      'holderId': instance.holderId,
      'holderAvatar': instance.holderAvatar,
      'holderNickName': instance.holderNickName,
      'holderWalletAddress': instance.holderWalletAddress,
      'status': instance.status,
      'synthesisStatus': instance.synthesisStatus,
      'activityStatus': instance.activityStatus,
      'transferType': instance.transferType,
      'allowSellTime': instance.allowSellTime,
      'isResale': instance.isResale,
      'onSales': instance.onSales,
      'stock': instance.stock,
      'isRestrictionSell': instance.isRestrictionSell,
      'payWay': instance.payWay,
      'isProductBatchTransfer': instance.isProductBatchTransfer,
      'isUserBatchTransfer': instance.isUserBatchTransfer,
      'type': instance.type,
      'isBoxPrize': instance.isBoxPrize,
      'notOpenNumber': instance.notOpenNumber,
      'productList': instance.productList,
      'dynamicImage': instance.dynamicImage,
    };
