// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Data _$DataFromJson(Map<String, dynamic> json) => Data(
      productSeriesId: json['productSeriesId'] as dynamic,
      orderId: json['orderId'] as dynamic,
      productId: json['productId'] as dynamic,
      productName: json['productName'] as dynamic,
      productImage: json['productImage'] as dynamic,
      productMintName: json['productMintName'] as dynamic,
      orderAmount: json['orderAmount'] as dynamic,
      actualAmount: json['actualAmount'] as dynamic,
      discountAmount: json['discountAmount'] as dynamic,
      orderTime: json['orderTime'] as dynamic,
      payTime: json['payTime'],
      orderStatus: json['orderStatus'] as dynamic,
      endDate: json['endDate'] as dynamic,
      finishDate: json['finishDate'],
      num: json['num'] as dynamic,
      orderType: json['orderType'] as dynamic,
      productMintId: json['productMintId'] as dynamic,
      productMintList: (json['productMintList'] as List<dynamic>?)
          ?.map((e) => ProductMintList.fromJson(e as Map<String, dynamic>))
          .toList(),
      resaleWalletAddress: json['resaleWalletAddress'],
      buyWalletAddress: json['buyWalletAddress'],
      chargeAmount: (json['chargeAmount'] as num?)?.toDouble(),
      predictAmount: (json['predictAmount'] as num?)?.toDouble(),
      feeRatio: json['feeRatio'] as dynamic,
      mintNumber: json['mintNumber'] as dynamic,
      tradeStatus: json['tradeStatus'],
      txHash: json['txHash'] as dynamic,
      activityId: json['activityId'],
      productShareImage: json['productShareImage'] as dynamic,
      payWay: json['payWay'] as dynamic,
      walletSource: json['walletSource'],
      userId: json['userId'] as dynamic,
      type: json['type'] as dynamic,
      lockStatus: json['lockStatus'] as dynamic,
      isBoxPrize: json['isBoxPrize'] as dynamic,
      batchOrder: json['batchOrder'] as bool?,
      isQuickOrder: json['isQuickOrder'] as dynamic,
    );

Map<String, dynamic> _$DataToJson(Data instance) => <String, dynamic>{
      'productSeriesId': instance.productSeriesId,
      'orderId': instance.orderId,
      'productId': instance.productId,
      'productName': instance.productName,
      'productImage': instance.productImage,
      'productMintName': instance.productMintName,
      'orderAmount': instance.orderAmount,
      'actualAmount': instance.actualAmount,
      'discountAmount': instance.discountAmount,
      'orderTime': instance.orderTime,
      'payTime': instance.payTime,
      'orderStatus': instance.orderStatus,
      'endDate': instance.endDate,
      'finishDate': instance.finishDate,
      'num': instance.num,
      'orderType': instance.orderType,
      'productMintId': instance.productMintId,
      'productMintList': instance.productMintList,
      'resaleWalletAddress': instance.resaleWalletAddress,
      'buyWalletAddress': instance.buyWalletAddress,
      'chargeAmount': instance.chargeAmount,
      'predictAmount': instance.predictAmount,
      'feeRatio': instance.feeRatio,
      'mintNumber': instance.mintNumber,
      'tradeStatus': instance.tradeStatus,
      'txHash': instance.txHash,
      'activityId': instance.activityId,
      'productShareImage': instance.productShareImage,
      'payWay': instance.payWay,
      'walletSource': instance.walletSource,
      'userId': instance.userId,
      'type': instance.type,
      'lockStatus': instance.lockStatus,
      'isBoxPrize': instance.isBoxPrize,
      'batchOrder': instance.batchOrder,
      'isQuickOrder': instance.isQuickOrder,
    };
