// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Data _$DataFromJson(Map<String, dynamic> json) => Data(
      current: json['current'] as int?,
      rows: json['rows'] as int?,
      id: json['id'] as String?,
      createDate: json['createDate'] as String?,
      updateDate: json['updateDate'] as String?,
      createBy: json['createBy'],
      updateBy: json['updateBy'] as String?,
      delFlag: json['delFlag'] as bool?,
      appCid: json['appCid'] as String?,
      openId: json['openId'],
      unionId: json['unionId'],
      appOpenId: json['appOpenId'],
      nickName: json['nickName'] as String?,
      avatar: json['avatar'] as String?,
      wxName: json['wxName'] as String?,
      phone: json['phone'] as String?,
      userType: json['userType'] as int?,
      state: json['state'] as int?,
      ibNum: json['ibNum'] as int?,
      freePaintCount: json['freePaintCount'] as int?,
      ticketsNum: json['ticketsNum'] as int?,
      achievementValue: json['achievementValue'] as int?,
      inviterId: json['inviterId'] as String?,
      officialFocusStatus: json['officialFocusStatus'] as int?,
      joinCommunityStatus: json['joinCommunityStatus'] as int?,
      isFirstPaint: json['isFirstPaint'] as int?,
      firstPaintDate: json['firstPaintDate'],
      loginDate: json['loginDate'] as String?,
      personalProfile: json['personalProfile'] as String?,
      walletAddress: json['walletAddress'] as String?,
      nftWalletAddress: json['nftWalletAddress'] as String?,
      isShowProduct: json['isShowProduct'] as int?,
      isShowSellProduct: json['isShowSellProduct'] as int?,
      isReceiveResaleSms: json['isReceiveResaleSms'] as int?,
      isReceiveSms: json['isReceiveSms'] as int?,
      postName: json['postName'] as String?,
      postPhone: json['postPhone'] as String?,
      postAddress: json['postAddress'] as String?,
      flowSource: json['flowSource'],
      realName: json['realName'] as String?,
      cardNo: json['cardNo'] as String?,
      authPassDate: json['authPassDate'],
      salePwd: json['salePwd'] as String?,
      payPwd: json['payPwd'],
      saleStatus: json['saleStatus'] as int?,
      buyStatus: json['buyStatus'] as int?,
      withdrawalStatus: json['withdrawalStatus'] as int?,
      inviteCode: json['inviteCode'] as String?,
      sn: json['sn'],
      isDestroy: json['isDestroy'] as int?,
      accL: json['accL'] as int?,
      accSn: json['accSn'],
      isAnonymous: json['isAnonymous'] as int?,
      isReadReplace: json['isReadReplace'] as int?,
      isReadDuobao: json['isReadDuobao'] as int?,
      paintCount: json['paintCount'],
      achievementNickName: json['achievementNickName'],
      addTicketNum: json['addTicketNum'],
      addIbNum: json['addIbNum'],
      reduceTicketNum: json['reduceTicketNum'],
      reduceIbNum: json['reduceIbNum'],
      addAchievementValue: json['addAchievementValue'],
      integralRecordNum: json['integralRecordNum'] as int?,
      addICoinNum: json['addICoinNum'],
      reduceICoinNum: json['reduceICoinNum'],
      addFreePaintCount: json['addFreePaintCount'],
      reduceFreePaintCount: json['reduceFreePaintCount'],
      integralNum: json['integralNum'],
      pid: json['pid'],
    );

Map<String, dynamic> _$DataToJson(Data instance) => <String, dynamic>{
      'current': instance.current,
      'rows': instance.rows,
      'id': instance.id,
      'createDate': instance.createDate,
      'updateDate': instance.updateDate,
      'createBy': instance.createBy,
      'updateBy': instance.updateBy,
      'delFlag': instance.delFlag,
      'appCid': instance.appCid,
      'openId': instance.openId,
      'unionId': instance.unionId,
      'appOpenId': instance.appOpenId,
      'nickName': instance.nickName,
      'avatar': instance.avatar,
      'wxName': instance.wxName,
      'phone': instance.phone,
      'userType': instance.userType,
      'state': instance.state,
      'ibNum': instance.ibNum,
      'freePaintCount': instance.freePaintCount,
      'ticketsNum': instance.ticketsNum,
      'achievementValue': instance.achievementValue,
      'inviterId': instance.inviterId,
      'officialFocusStatus': instance.officialFocusStatus,
      'joinCommunityStatus': instance.joinCommunityStatus,
      'isFirstPaint': instance.isFirstPaint,
      'firstPaintDate': instance.firstPaintDate,
      'loginDate': instance.loginDate,
      'personalProfile': instance.personalProfile,
      'walletAddress': instance.walletAddress,
      'nftWalletAddress': instance.nftWalletAddress,
      'isShowProduct': instance.isShowProduct,
      'isShowSellProduct': instance.isShowSellProduct,
      'isReceiveResaleSms': instance.isReceiveResaleSms,
      'isReceiveSms': instance.isReceiveSms,
      'postName': instance.postName,
      'postPhone': instance.postPhone,
      'postAddress': instance.postAddress,
      'flowSource': instance.flowSource,
      'realName': instance.realName,
      'cardNo': instance.cardNo,
      'authPassDate': instance.authPassDate,
      'salePwd': instance.salePwd,
      'payPwd': instance.payPwd,
      'saleStatus': instance.saleStatus,
      'buyStatus': instance.buyStatus,
      'withdrawalStatus': instance.withdrawalStatus,
      'inviteCode': instance.inviteCode,
      'sn': instance.sn,
      'isDestroy': instance.isDestroy,
      'accL': instance.accL,
      'accSn': instance.accSn,
      'isAnonymous': instance.isAnonymous,
      'isReadReplace': instance.isReadReplace,
      'isReadDuobao': instance.isReadDuobao,
      'paintCount': instance.paintCount,
      'achievementNickName': instance.achievementNickName,
      'addTicketNum': instance.addTicketNum,
      'addIbNum': instance.addIbNum,
      'reduceTicketNum': instance.reduceTicketNum,
      'reduceIbNum': instance.reduceIbNum,
      'addAchievementValue': instance.addAchievementValue,
      'integralRecordNum': instance.integralRecordNum,
      'addICoinNum': instance.addICoinNum,
      'reduceICoinNum': instance.reduceICoinNum,
      'addFreePaintCount': instance.addFreePaintCount,
      'reduceFreePaintCount': instance.reduceFreePaintCount,
      'integralNum': instance.integralNum,
      'pid': instance.pid,
    };
