// GENERATED CODE - DO NOT MODIFY BY HAND

part of 'data.dart';

// **************************************************************************
// JsonSerializableGenerator
// **************************************************************************

Data _$DataFromJson(Map<String, dynamic> json) => Data(
      current: json['current'] as int?,
      rows: json['rows'] as int?,
      id: json['id'] as String?,
      createDate: json['createDate'] as String?,
      updateDate: json['updateDate'] as String?,
      createBy: json['createBy'] as String?,
      updateBy: json['updateBy'] as String?,
      delFlag: json['delFlag'] as bool?,
      type: json['type'] as String?,
      typeName: json['typeName'],
      sendUserType: json['sendUserType'] as int?,
      exhibitionId: json['exhibitionId'],
      rankUserId: json['rankUserId'],
      title: json['title'] as String?,
      content: json['content'] as String?,
      pageType: json['pageType'],
      appletUrl: json['appletUrl'],
      redirectUrl: json['redirectUrl'] as String?,
      clickCount: json['clickCount'] as int?,
      state: json['state'] as int?,
      publishWay: json['publishWay'] as int?,
      autoPublishTime: json['autoPublishTime'],
      publishTime: json['publishTime'] as String?,
      publishBy: json['publishBy'] as String?,
      imgUrl: json['imgUrl'] as String?,
      isSyncGroup: json['isSyncGroup'] as int?,
      productIds: json['productIds'] as String?,
      activityIds: json['activityIds'],
      activityType: json['activityType'] as int?,
      isBounceWindow: json['isBounceWindow'] as int?,
      isPushNotice: json['isPushNotice'] as int?,
      pushUserType: json['pushUserType'] as int?,
      holdProductId: json['holdProductId'] as String?,
      pushTitle: json['pushTitle'] as String?,
      pushContent: json['pushContent'] as String?,
      isSendResaleSms: json['isSendResaleSms'] as int?,
      resaleHoldProductId: json['resaleHoldProductId'] as String?,
      productList: json['productList'],
      activityList: json['activityList'],
      userId: json['userId'],
      exhibitionName: json['exhibitionName'],
      readFlag: json['readFlag'] as int?,
      searchParam: json['searchParam'],
    );

Map<String, dynamic> _$DataToJson(Data instance) => <String, dynamic>{
      'current': instance.current,
      'rows': instance.rows,
      'id': instance.id,
      'createDate': instance.createDate,
      'updateDate': instance.updateDate,
      'createBy': instance.createBy,
      'updateBy': instance.updateBy,
      'delFlag': instance.delFlag,
      'type': instance.type,
      'typeName': instance.typeName,
      'sendUserType': instance.sendUserType,
      'exhibitionId': instance.exhibitionId,
      'rankUserId': instance.rankUserId,
      'title': instance.title,
      'content': instance.content,
      'pageType': instance.pageType,
      'appletUrl': instance.appletUrl,
      'redirectUrl': instance.redirectUrl,
      'clickCount': instance.clickCount,
      'state': instance.state,
      'publishWay': instance.publishWay,
      'autoPublishTime': instance.autoPublishTime,
      'publishTime': instance.publishTime,
      'publishBy': instance.publishBy,
      'imgUrl': instance.imgUrl,
      'isSyncGroup': instance.isSyncGroup,
      'productIds': instance.productIds,
      'activityIds': instance.activityIds,
      'activityType': instance.activityType,
      'isBounceWindow': instance.isBounceWindow,
      'isPushNotice': instance.isPushNotice,
      'pushUserType': instance.pushUserType,
      'holdProductId': instance.holdProductId,
      'pushTitle': instance.pushTitle,
      'pushContent': instance.pushContent,
      'isSendResaleSms': instance.isSendResaleSms,
      'resaleHoldProductId': instance.resaleHoldProductId,
      'productList': instance.productList,
      'activityList': instance.activityList,
      'userId': instance.userId,
      'exhibitionName': instance.exhibitionName,
      'readFlag': instance.readFlag,
      'searchParam': instance.searchParam,
    };
